management:
    endpoint:
        health:
            probes:
                enabled: true
        prometheus:
            enabled: true
    endpoints:
        web:
            exposure:
                include: health,env,metrics,beans,loggers,prometheus
    tracing:
        sampling:
            probability: 0.01
spring:
    application:
        name: football
    jpa:
        database-platform: org.hibernate.dialect.PostgreSQLDialect
        open-in-view: false
#        show-sql: true
    datasource:
        url: jdbc:postgresql://localhost:5432/football
        username: packt
        password: packt
    # native:
    #     image-hints: org.springframework.data.domain.Unpaged
